"""v9_pdf_monthly_report.py — Phase 88 motion CEO 48H (post-Plan C).

Genere un rapport HTML mensuel des performances V9.
Sections : summary, trades, edges (L1-L17 actifs).

Auteur : Hermes (Phase 88 motion CEO 48H non-stop, 31/07/2026)
"""
from __future__ import annotations

import argparse
import datetime
import logging
from pathlib import Path
from typing import Any

log = logging.getLogger("v9.pdf_monthly")

REPORT_SECTIONS = ["summary", "trades", "edges"]

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>V9 Monthly Report {month}</title>
  <style>
    body {{ font-family: -apple-system, sans-serif; margin: 20px;
            background: #0d1117; color: #c9d1d9; }}
    h1, h2 {{ color: #58a6ff; }}
    table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
    th, td {{ border: 1px solid #30363d; padding: 8px; text-align: left; }}
    th {{ background: #161b22; }}
    .summary {{ background: #161b22; padding: 15px; border-radius: 6px;
                margin: 20px 0; }}
    .positive {{ color: #3fb950; }}
    .negative {{ color: #f85149; }}
  </style>
</head>
<body>
  <h1>V9 Monthly Report — {month}</h1>
  {summary_section}
  {trades_section}
  {edges_section}
  <p><small>Generated by v9_pdf_monthly_report.py — Phase 88</small></p>
</body>
</html>
"""


def format_summary_html(
    wr: float, n_trades: int, total_pips: float,
    sharpe: float, max_dd: float, pf: float,
) -> str:
    """Genere la section summary en HTML."""
    wr_class = "positive" if wr >= 0.60 else "negative"
    pips_class = "positive" if total_pips >= 0 else "negative"
    return f"""<div class="summary">
  <h2>Summary</h2>
  <p><b>Win Rate</b> : <span class="{wr_class}">{wr*100:.2f}%</span></p>
  <p><b>N Trades</b> : {n_trades}</p>
  <p><b>Total Pips</b> : <span class="{pips_class}">{total_pips:+.1f}</span></p>
  <p><b>Sharpe</b> : {sharpe:.2f}</p>
  <p><b>Max DD</b> : {max_dd:.1f} pips</p>
  <p><b>Profit Factor</b> : {pf:.2f}</p>
</div>"""


def format_trades_table(trades: list[dict[str, Any]]) -> str:
    """Genere le tableau HTML des trades."""
    if not trades:
        return "<h2>Trades</h2><p>No trades.</p>"
    rows = []
    for t in trades[:50]:  # max 50 lignes
        cls = "positive" if t["is_win"] else "negative"
        rows.append(
            f"<tr><td>{t['timestamp']}</td>"
            f"<td>{t['symbol']}</td>"
            f"<td class='{cls}'>{t['pips']:+.1f}</td></tr>",
        )
    return (
        "<h2>Trades</h2>"
        "<table><thead><tr>"
        "<th>Timestamp</th><th>Symbol</th><th>Pips</th>"
        "</tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def format_edges_table(edges: list[dict[str, Any]]) -> str:
    """Genere le tableau HTML des edges actifs."""
    if not edges:
        return "<h2>Edges</h2><p>No edges.</p>"
    rows = []
    for e in edges:
        cls = "positive" if e["total_pips"] >= 0 else "negative"
        rows.append(
            f"<tr><td>{e['name']}</td>"
            f"<td>{e['wr']*100:.1f}%</td>"
            f"<td>{e['n_trades']}</td>"
            f"<td class='{cls}'>{e['total_pips']:+.1f}</td></tr>",
        )
    return (
        "<h2>Edges (L1-L17)</h2>"
        "<table><thead><tr>"
        "<th>Lever</th><th>WR</th><th>N Trades</th><th>Total Pips</th>"
        "</tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def generate_full_html(data: dict[str, Any]) -> str:
    """Genere le rapport HTML complet."""
    summary = format_summary_html(
        wr=data.get("wr", 0),
        n_trades=data.get("n_trades", 0),
        total_pips=data.get("total_pips", 0),
        sharpe=data.get("sharpe", 0),
        max_dd=data.get("max_dd", 0),
        pf=data.get("pf", 0),
    )
    trades_html = format_trades_table(data.get("trades", []))
    edges_html = format_edges_table(data.get("edges", []))
    return HTML_TEMPLATE.format(
        month=data.get("month", "unknown"),
        summary_section=summary,
        trades_section=trades_html,
        edges_section=edges_html,
    )


def export_html(html: str, output_path: Path) -> bool:
    """Exporte le rapport HTML dans un fichier."""
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
        return True
    except Exception as exc:
        log.warning("export_html failed: %s", exc)
        return False


def main(argv=None) -> int:
    """Genere le rapport mensuel."""
    parser = argparse.ArgumentParser(description="V9 monthly PDF/HTML report")
    parser.add_argument("--output", default="./docs/v9_report.html")
    parser.add_argument("--month", default=datetime.date.today().strftime("%Y-%m"))
    args = parser.parse_args(argv)
    print("=" * 70)
    print("V9 MONTHLY REPORT (Phase 88)")
    print("=" * 70)
    print(f"Month  : {args.month}")
    print(f"Output : {args.output}")
    # Demo data (en prod : lecture depuis DB)
    data = {
        "month": args.month,
        "wr": 0.85, "n_trades": 100, "total_pips": 500.0,
        "sharpe": 1.2, "max_dd": 50.0, "pf": 2.5,
        "trades": [
            {"timestamp": "2026-07-31T12:00:00", "symbol": "GBPUSD",
             "pips": 25.0, "is_win": True},
            {"timestamp": "2026-07-31T14:00:00", "symbol": "EURUSD",
             "pips": -8.0, "is_win": False},
        ],
        "edges": [
            {"name": "L1 GBPUSD 11-13h", "wr": 0.95, "n_trades": 50,
             "total_pips": 250.0},
            {"name": "L8 NEUTRE blacklist", "wr": 0.25, "n_trades": 30,
             "total_pips": -200.0},
        ],
    }
    html = generate_full_html(data)
    out = Path(args.output)
    ok = export_html(html, out)
    print(f"Generated : {ok}")
    if ok:
        print(f"Size      : {out.stat().st_size} bytes")
    print("=" * 70)
    return 0 if ok else 1


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    import sys
    sys.exit(main())